import type { JournalEntry } from "./portfolio";

/**
 * GENERATED by scripts/build-journal.mjs. Do not edit by hand.
 *
 * Source: https://github.com/MLDuke/sketchbook/blob/main
 */
export const journalEntries: JournalEntry[] = [];
